if(NOT DEFINED SOURCE_PRESETS OR NOT DEFINED DESTINATION OR NOT DEFINED SOURCE_REVISION)
  message(FATAL_ERROR "SOURCE_PRESETS, DESTINATION, and SOURCE_REVISION are required")
endif()

file(REMOVE_RECURSE "${DESTINATION}")
file(MAKE_DIRECTORY "${DESTINATION}")

file(GLOB preset_entries LIST_DIRECTORIES true "${SOURCE_PRESETS}/*")
set(preset_ids)
foreach(preset_entry IN LISTS preset_entries)
  if(IS_DIRECTORY "${preset_entry}" AND EXISTS "${preset_entry}/definition.json")
    get_filename_component(preset_id "${preset_entry}" NAME)
    list(APPEND preset_ids "${preset_id}")
    file(MAKE_DIRECTORY "${DESTINATION}/${preset_id}")
    file(COPY "${preset_entry}/definition.json" DESTINATION "${DESTINATION}/${preset_id}")
  endif()
endforeach()

list(SORT preset_ids)
if(EXISTS "${SOURCE_PRESETS}/assets")
  file(COPY "${SOURCE_PRESETS}/assets/" DESTINATION "${DESTINATION}/assets")
endif()

set(manifest "{\n  \"sourceRevision\": \"${SOURCE_REVISION}\",\n  \"presets\": [")
set(first_preset TRUE)
foreach(preset_id IN LISTS preset_ids)
  if(first_preset)
    set(first_preset FALSE)
  else()
    string(APPEND manifest ",")
  endif()
  string(APPEND manifest "\n    \"${preset_id}\"")
endforeach()
string(APPEND manifest "\n  ]\n}\n")
file(WRITE "${DESTINATION}/manifest.json" "${manifest}")
